tmp: use GIT_PRIVATE_IP from enviroment, not auto detect

diff --git a/scripts/run b/scripts/run
--- a/scripts/run
+++ b/scripts/run
@@ -365,21 +365,26 @@ _repo_create_default() {
 _repo_init() {
 	_git_config
 	mkdir -p $ROOT_DIR/data $ROOT_DIR/env
-	ip=$(curl http://ipv4.canhazip.com)
-	GIT_PRIVATE_DOMAIN=git.$DOMAIN
-	_add_host $GIT_PRIVATE_DOMAIN $ip
-
-	if [ ! -f "$VARS/GIT_PRIVATE_DOMAIN" ]; then
-		echo "$GIT_PRIVATE_DOMAIN" >$VARS/GIT_PRIVATE_DOMAIN
-	else
-		GIT_PRIVATE_DOMAIN=$(cat $VARS/GIT_PRIVATE_DOMAIN)
+	if [ -z "$DOMAIN" ]; then
+		echo "environment DOMAIN missing"
+		exit 1
 	fi
 
-	if [ ! -f "$VARS/GIT_PRIVATE_IP" ]; then
-		echo "$ip" >$VARS/GIT_PRIVATE_IP
-	else
-		GIT_PRIVATE_IP=$(cat $VARS/GIT_PRIVATE_IP)
-	fi
+	# ip=$(curl http://ipv4.canhazip.com)
+	# GIT_PRIVATE_DOMAIN=git.$DOMAIN
+	# _add_host $GIT_PRIVATE_DOMAIN $ip
+
+	# if [ ! -f "$VARS/GIT_PRIVATE_DOMAIN" ]; then
+	# 	echo "$GIT_PRIVATE_DOMAIN" >$VARS/GIT_PRIVATE_DOMAIN
+	# else
+	GIT_PRIVATE_DOMAIN=${GIT_PRIVATE_DOMAIN:-git.$DOMAIN}
+	# fi
+
+	# if [ ! -f "$VARS/GIT_PRIVATE_IP" ]; then
+	# 	echo "$ip" >$VARS/GIT_PRIVATE_IP
+	# else
+	# 	GIT_PRIVATE_IP=$(cat $VARS/GIT_PRIVATE_IP)
+	# fi
 
 	if [ ! -f "$VARS/GIT_PRIVATE_READ" ]; then
 		GIT_PRIVATE_READ=massbit:$(_passwd)
