dev: remove update env

diff --git a/scripts/run b/scripts/run
--- a/scripts/run
+++ b/scripts/run
@@ -4,28 +4,32 @@ SITE_ROOT=$(realpath $(dirname $(realpath $0))/..)
 mkdir -p $SITE_ROOT
 
 export HOME=$SITE_ROOT
-
+# $service_dir/git|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_git.git|$GIT_BRANCH \
+# $mbr_root/gbc|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_gbc|$GBC_BRANCH \
 _repo() {
-	if [ -e "$SITE_ROOT/cmd_server" ]; then bash $SITE_ROOT/cmd_server _env; fi
-	if [ -f "$SITE_ROOT/.env_raw" ]; then source $SITE_ROOT/.env_raw; fi
-	export MBR_ENV=${MBR_ENV:-dev}
-	export MBRAPP_BRANCH=${MBRAPP_BRANCH:-$MBR_ENV}
-	export ASDF_BRANCH=${ASDF_BRANCH:-$MBR_ENV}
-	export GBC_BRANCH=${GBC_BRANCH:-$MBR_DEV}
-	export SSL_BRANCH=${SSL_BRANCH:-$MBR_ENV}
-	export GWMAN_BRANCH=${GWMAN_BRANCH:-$MBR_ENV}
-	export NODE_BRANCH=${NODE_BRANCH:-$MBR_ENV}
-	export GATEWAY_BRANCH=${GATEWAY_BRANCH:-$MBR_ENV}
-	export STAT_BRANCH=${STAT_BRANCH:-$MBR_ENV}
-	export MONITOR_BRANCH=${MONITOR_BRANCH:-$MBR_ENV}
-	export MONITORDEPLOY_BRANCH=${MONITORDEPLOY_BRANCH:-$MBR_ENV}
-	export API_BRANCH=${API_BRANCH:-$MBR_ENV}
-	export SESSION_BRANCH=${SESSION_BRANCH:-$MBR_ENV}
-	export GIT_BRANCH=${GIT_BRANCH:-$MBR_DEV}
+	if [ -z "$MBR_ENV" ]; then
+		echo "MBR_ENV missing"
+		exit 1
+	fi
+
+	# if [ -e "$SITE_ROOT/cmd_server" ]; then bash $SITE_ROOT/cmd_server _env; fi
+	# if [ -f "$SITE_ROOT/.env_raw" ]; then source $SITE_ROOT/.env_raw; fi
+	# export MBR_ENV=${MBR_ENV:-keiko}
+	# export MBRAPP_BRANCH=${MBRAPP_BRANCH:-$MBR_ENV}
+	# export ASDF_BRANCH=${ASDF_BRANCH:-$MBR_ENV}
+	# export GBC_BRANCH=${GBC_BRANCH:-$MBR_DEV}
+	# export SSL_BRANCH=${SSL_BRANCH:-$MBR_ENV}
+	# export GWMAN_BRANCH=${GWMAN_BRANCH:-$MBR_ENV}
+	# export NODE_BRANCH=${NODE_BRANCH:-$MBR_ENV}
+	# export GATEWAY_BRANCH=${GATEWAY_BRANCH:-$MBR_ENV}
+	# export STAT_BRANCH=${STAT_BRANCH:-$MBR_ENV}
+	# export MONITOR_BRANCH=${MONITOR_BRANCH:-$MBR_ENV}
+	# export MONITORDEPLOY_BRANCH=${MONITORDEPLOY_BRANCH:-$MBR_ENV}
+	# export API_BRANCH=${API_BRANCH:-$MBR_ENV}
+	# export SESSION_BRANCH=${SESSION_BRANCH:-$MBR_ENV}
+	# export GIT_BRANCH=${GIT_BRANCH:-$MBR_DEV}
 	export MKAGENT_BRANCH=${MKAGENT_BRANCH:-$MBR_ENV}
 	REPOS="\
- $mbr_root/gbc|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_gbc|$GBC_BRANCH \
-  $service_dir/git|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_git.git|$GIT_BRANCH \
   $service_dir/mkagent|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_mkagent.git|$MKAGENT_BRANCH \
 "
 }
